environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"

os: Visual Studio 2015
platform: x64

cache:
  - node_modules


install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - cmake --version
  - npm test

build: off