init:
  - git config --global core.autocrlf true

os: 
  Visual Studio 2015

environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "9"

platform: 
  - x86
  - x64

# cache:
#   - node_modules

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm -g install npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install -a %PLATFORM%
  - echo %PLATFORM%
  
matrix:
  fast_finish: true

test_script:
  - node --version
  - npm --version
  - cmake --version
  - npm test

build: 
  off